Repository kubeslice/kubeslice-controller, pull requests merged in 2022-09, with the labels that each got.

#76 IPAM upgrade fix
  apis/worker/v1alpha1/workersliceconfig_types.go
  apis/worker/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/worker.kubeslice.io_workersliceconfigs.yaml
  service/worker_slice_config_service.go
  service/worker_slice_config_service_test.go
  service/worker_slice_config_webhook_validation.go
  service/worker_slice_config_webhook_validation_test.go
Labels: bug, enhancement

#81 quality gate added
  .github/workflows/end-to-end-test.yaml
  .github/workflows/scripts/start-kind.sh
  quality-gate/action.yml
Labels: ready-to-test

#84 Dev to master sync
  service/slice_config_webhook_validation.go
Labels: bug, ready-to-test
